//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceHostingApplication.PerSessionWcfServiceClient {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PerSessionWcfServiceClient.IPerSessionWcfService")]
    public interface IPerSessionWcfService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerSessionWcfService/SleepForMilliseconds", ReplyAction="http://tempuri.org/IPerSessionWcfService/SleepForMillisecondsResponse")]
        System.Guid SleepForMilliseconds(int ms, System.Guid guid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerSessionWcfService/SleepForMilliseconds", ReplyAction="http://tempuri.org/IPerSessionWcfService/SleepForMillisecondsResponse")]
        System.Threading.Tasks.Task<System.Guid> SleepForMillisecondsAsync(int ms, System.Guid guid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerSessionWcfService/BusySleepForMilliseconds", ReplyAction="http://tempuri.org/IPerSessionWcfService/BusySleepForMillisecondsResponse")]
        System.Guid BusySleepForMilliseconds(int ms, System.Guid guid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerSessionWcfService/BusySleepForMilliseconds", ReplyAction="http://tempuri.org/IPerSessionWcfService/BusySleepForMillisecondsResponse")]
        System.Threading.Tasks.Task<System.Guid> BusySleepForMillisecondsAsync(int ms, System.Guid guid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerSessionWcfService/TaskedSleepForMilliseconds", ReplyAction="http://tempuri.org/IPerSessionWcfService/TaskedSleepForMillisecondsResponse")]
        System.Guid TaskedSleepForMilliseconds(int ms, System.Guid guid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerSessionWcfService/TaskedSleepForMilliseconds", ReplyAction="http://tempuri.org/IPerSessionWcfService/TaskedSleepForMillisecondsResponse")]
        System.Threading.Tasks.Task<System.Guid> TaskedSleepForMillisecondsAsync(int ms, System.Guid guid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerSessionWcfService/TaskedBusySleepForMilliseconds", ReplyAction="http://tempuri.org/IPerSessionWcfService/TaskedBusySleepForMillisecondsResponse")]
        System.Guid TaskedBusySleepForMilliseconds(int ms, System.Guid guid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerSessionWcfService/TaskedBusySleepForMilliseconds", ReplyAction="http://tempuri.org/IPerSessionWcfService/TaskedBusySleepForMillisecondsResponse")]
        System.Threading.Tasks.Task<System.Guid> TaskedBusySleepForMillisecondsAsync(int ms, System.Guid guid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerSessionWcfService/GetData", ReplyAction="http://tempuri.org/IPerSessionWcfService/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerSessionWcfService/GetData", ReplyAction="http://tempuri.org/IPerSessionWcfService/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerSessionWcfService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IPerSessionWcfService/GetDataUsingDataContractResponse")]
        SharedLib.CompositeType GetDataUsingDataContract(SharedLib.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerSessionWcfService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IPerSessionWcfService/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<SharedLib.CompositeType> GetDataUsingDataContractAsync(SharedLib.CompositeType composite);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPerSessionWcfServiceChannel : ServiceHostingApplication.PerSessionWcfServiceClient.IPerSessionWcfService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PerSessionWcfServiceClient : System.ServiceModel.ClientBase<ServiceHostingApplication.PerSessionWcfServiceClient.IPerSessionWcfService>, ServiceHostingApplication.PerSessionWcfServiceClient.IPerSessionWcfService {
        
        public PerSessionWcfServiceClient() {
        }
        
        public PerSessionWcfServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PerSessionWcfServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PerSessionWcfServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PerSessionWcfServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Guid SleepForMilliseconds(int ms, System.Guid guid) {
            return base.Channel.SleepForMilliseconds(ms, guid);
        }
        
        public System.Threading.Tasks.Task<System.Guid> SleepForMillisecondsAsync(int ms, System.Guid guid) {
            return base.Channel.SleepForMillisecondsAsync(ms, guid);
        }
        
        public System.Guid BusySleepForMilliseconds(int ms, System.Guid guid) {
            return base.Channel.BusySleepForMilliseconds(ms, guid);
        }
        
        public System.Threading.Tasks.Task<System.Guid> BusySleepForMillisecondsAsync(int ms, System.Guid guid) {
            return base.Channel.BusySleepForMillisecondsAsync(ms, guid);
        }
        
        public System.Guid TaskedSleepForMilliseconds(int ms, System.Guid guid) {
            return base.Channel.TaskedSleepForMilliseconds(ms, guid);
        }
        
        public System.Threading.Tasks.Task<System.Guid> TaskedSleepForMillisecondsAsync(int ms, System.Guid guid) {
            return base.Channel.TaskedSleepForMillisecondsAsync(ms, guid);
        }
        
        public System.Guid TaskedBusySleepForMilliseconds(int ms, System.Guid guid) {
            return base.Channel.TaskedBusySleepForMilliseconds(ms, guid);
        }
        
        public System.Threading.Tasks.Task<System.Guid> TaskedBusySleepForMillisecondsAsync(int ms, System.Guid guid) {
            return base.Channel.TaskedBusySleepForMillisecondsAsync(ms, guid);
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public SharedLib.CompositeType GetDataUsingDataContract(SharedLib.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<SharedLib.CompositeType> GetDataUsingDataContractAsync(SharedLib.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
    }
}
